### ISSUE TITLE
Megamorphism

### ISSUE THREAD

**Issue by conartist6** [Farenheith/faster-readline-iterator#2]
You're missing an easy win when you create an iterator step object as `{ value }`. This creates megamorphism in all other code that deals with iterators because it is no longer trivial to evaluate the expression `step.done`. If `done` was always the first property in a step object, inline caches would recognize this and emit code for memory access with fixed (`0`) offset. But actually they have to account for two possible memory locations that could contain `step.done`, which is slower.

**Comment by Farenheith** [comment]
Thank you. I'll look into that.

**Comment by Farenheith** [comment]
Solved in 0.1.0
